### ISSUE TITLE
Repository `https://github.com/langfield/gitpython.git/` not found

### ISSUE THREAD

**Issue by la-marc** [langfield/ki#112]
Hi,

I'm getting an error as in the title when trying to install.
A quick check shows that this address does indeed appear in requirements.txt.

I'm trying to use termux for the install (and see if I can use ki with AnkiDroid that way), which probably doesn't help.

**Comment by langfield** [comment]
@la-marc Thanks so much for bringing this to my attention! Yes, it appears the dependency tree has decayed a bit. What likely happened is that at some point within the past couple months, I went through my forks and deleted most of them. Probably got `GitPython` by accident.

In any case, the reason why I was using a fork was because a certain fix hadn't been merged yet. However, I believe they accepted my PR long ago, so we should be good-to-go.

I've pushed a fix straight to `master`. Try it now and see if you have better luck!

Hmm, getting it working on AnkiDroid is not inconceivable, provided you have `git` working on `termux`, and the Anki database is laid out in the same way as on desktop. Let me know if you run into any trouble and I'd be glad to help you any way I can! 😁

**Comment by la-marc** [comment]
Nice, thanks!

It does seem to solve the problem in the title and the installation progresses a bit.
However, another problem arises: it seems that the python anki (installed through pip) becomes OS specific from version 2.1.36 on (judging from the pypi files for different versions). So, I'm only getting an older version of anki when running pip install anki (and forcing upgrades doesn't help). This was not a problem on my Linux machine.
Regarding html-tidy, termux does have a package for that, so maybe that part would work.

For now, I think I will stick to the "traditional way" of syncing with the Desktop first and using ki there.
Thanks for offering help, anyways! I have also an unrelated question, that I state in a separate thread.

**Comment by langfield** [comment]
Yes, unfortunately, the current "stable" version of this tool has a hard dependency on the PyPI package `anki`.

However, I've been working on a ground-up rewrite in Haskell for a month or so now, and this version will not depend on anything, as I plan to simply distribute statically linked binaries for all supported platforms. It may be quite a while before that gets merged, though.

I think versioning your decks on a single host is probably the way to go. If you use the desktop somewhat frequently (probably to make or edit cards), then you probably want your source control to live there. Otherwise, you'll be merging more frequently than necessary if you're syncing the databases to each other and also pulling and pushing from some remote from both local repositories.

Having Ki on two devices is probably only useful for the case where Anki wants you to overwrite in one direction or the other, and you *really, really don't want to*. In that case, you can `pull` into your repositories on both ends, and then push one to a remote, and pull the remote into the other to fix conflicts manually.

**Comment by la-marc** [comment]
Sure, the dependence on anki package is fully understood.
Still, it was worth giving a shot :).

Yeah, having to work on Desktop won't be very limiting.

**Comment by langfield** [comment]
Great! Closing this as it is fixed.
