### ISSUE TITLE
Pushing a new note with an empty `guid` field raises a `BeartypeCallHintParamViolation`

### ISSUE THREAD

**Issue by la-marc** [langfield/ki#113]
Hi,

I have setup ki on my desktop. I did manage to perform a simple test involving pulling, changing one note and pushing and this seemed to work fine.
However, I am not entirely sure how should I go about creating a new note.
I've created a new markdown note (a copy of existing one with minor modifications) and deleted the guid (as I assumed this should not repeat among the notes). This did not work, however. Then I have put some string of symbols as guid and it did work.
I assume there should be some cosistent way of creating new notes / assigining guids.

The documentation includes a whole list of functions and some of them seem appropriate for this task (e.g. "get_guid"). I am not sure, however, how to call these functions to get them to work.

**Comment by langfield** [comment]
Hi! Yes, the way this is intended to work is that you leave the `guid` blank when creating a new note, and then `ki` is supposed to generate it for you using `get_guid()`.

You must have uncovered a bug. If you would post the full stack trace and error message you got when you tried pushing a commit with a blank `guid`, I would be happy to fix it for you. My guess is that this is a parsing error. Perhaps the grammar makes a bad assumption.

In any case, this is a very minor issue and should be very easy to fix!

**Comment by langfield** [comment]
@la-marc I've identified the issue and pushed a candidate fix for the bug. Try reinstalling to get on version `0.0.8a` and see if that works for you!

**Comment by la-marc** [comment]
Great, thanks!

I have tested the newest version and it works.
It is quite sensitive to how the note is written. It is no longer a problem for me once I got the working template, but I will describe the minor errors I hit on the way.
So, initially it did not return any error, but the new card just wouldn't appear in Anki Desktop.
Then I've put "guid:" with a space afterwards, which seemed to be the correct thing to do -- some progress was made, and I started getting an error complaining aboout the Back field not looking as expected -- the problem was there was no new line (\n) at the end.
Then I was getting an error about something being a dict and not a list -- I guess this is precisely what you have corrected now.

Thanks again for the fix!

**Comment by langfield** [comment]
Thanks, your description of the problems you ran into is _extremely_ valuable to me. I will keep these things in mind when writing documentation and designing the next release.

> So, initially it did not return any error, but the new card just wouldn't appear in Anki Desktop.

I suppose this is the most worrying to me. Do you think you can provide the source code for the markdown note you added when this happened?

> Then I've put "guid:" with a space afterwards, which seemed to be the correct thing to do -- some progress was made, and I started getting an error complaining aboout the Back field not looking as expected -- the problem was there was no new line (\n) at the end.

This is expected behavior, though I will think about changing it now that you have raised the concern.

Basically, I had two options when writing the grammar for the markdown notes:
* Account for as many variations of the correct syntax as possible (extra spaces, extra newlines, punctuation, etc). The problem with this approach is that it becomes unclear what the *correct* way of doing things is. There will be many variations/styles in codebases, and it will be a big mess for anybody trying to search or deserialize this format.
* Make a very strict, single way of writing notes, and have the parser emit errors whenever that is violated.

This is sort of analogous to the difference between YAML and JSON. In my experience, working with JSON is much nicer because there is no ambiguity, things work faster, it's supported in more places. This is the reason for this decision.

What I hope to do is get a clear understanding of which of these common formatting errors people will run into most often, and then write custom error messages that say something like:
```console
Error parsing 'note.md': missing trailing newline in field 'Back'
```

**Comment by langfield** [comment]
If you think it should work differently, or you have in mind some instructions I should have written somewhere, or something else that the tool should print out, please let me know!

**Comment by la-marc** [comment]
I agree with the approach; once I've started getting errors with some messages I was on a way to get the working template (modulo the problem with dict vs list). It might be useful, however, to mention in the documentation, how creating a new note is supposed to work -- it was no clear to me whether "deleting the word guid completely, or typing guid: with nothing afterwards or maybe something else was the way to go. And maybe providing one working example/template of a note that works for creating a new note.

My note was very simple, something like:
`
# Note
```

notetype: basic+
```

### Tags
```
1
label
testing
```

## Front
test2

## Back
testtesttest
`

or

`
# Note
```
guid:
notetype: basic+
```

### Tags
```
1
label
testing
```

## Front
test2

## Back
testtesttest
`

Besides not having "guid:" at all, or the space after "guid:", another problem with this note was that the Front was the same as of another card I already had. Once the error messages started to appear (which was after correcting guid), I was notified of this.

**Comment by langfield** [comment]
@la-marc You're absolutely right, I definitely do need something like this in the documentation. Please feel free to let me know about any other issues you run into or general feedback about the tool!
