### ISSUE TITLE
Clone raises `GitCommandError` on `git < 2.28` (`error: unknown option 'initial-branch=main'`)

### ISSUE THREAD

**Issue by AkimParis** [langfield/ki#118]
Hello guys!

Thank you for working on Ki!

I am a little bit confused by the first step - Cloning. Please correct me if I am wrong. 
As a Windows user, my path is at C:\Users\Kikisss\AppData\Roaming\Anki2\User 1 and I perfectly found my collection.anki2.

As stated, I am staying within the directory to clone the collection with ki clone collection.anki2.
It's cloning, notes, medias, fields, and decks at 100%... but I got an error as below.

cmd.py raised GitCommandError(redcated_command, status, sterr_value, stdout_vale)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
 cmdline: git init --initial-branch=main
 stderr: 'error: unknown option `initial-branch=main'

I am on Windows via Anaconda. I carefully installed Tidy with Chocolatey and Git. 
Any advice?  Thx! 

![Ki-test](https://user-images.githubusercontent.com/58808904/212131798-77208d11-c370-4342-a0a7-30cd2229da7a.jpg)

**Comment by langfield** [comment]
I'll look into this ASAP! Looks like just a compatibility problem. I guess some versions of git don't have that CLI flag.
________________________________
From: AkimParis ***@***.***>
Sent: Thursday, January 12, 2023 12:02:07 PM
To: langfield/ki ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [langfield/ki] Cloning Error (Issue #118)

Hello guys! Thank you for working on Ki! I am a little bit confused by the first step - Cloning. Please correct me if I am wrong. As a Windows user, my path is at C: \Users\Kikisss\AppData\Roaming\Anki2\User 1 and I perfectly found my collection. anki2. 


Hello guys!

Thank you for working on Ki!

I am a little bit confused by the first step - Cloning. Please correct me if I am wrong.
As a Windows user, my path is at C:\Users\Kikisss\AppData\Roaming\Anki2\User 1 and I perfectly found my collection.anki2.

As stated, I am staying within the directory to clone the collection with ki clone collection.anki2.
It's cloning, notes, medias, fields, and decks at 100%... but I got an error as below.

cmd.py raised GitCommandError(redcated_command, status, sterr_value, stdout_vale)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
cmdline: git init --initial-branch=main
stderr: 'error: unknown option `initial-branch=main'

I am on Windows via Anaconda. I carefully installed Tidy with Chocolatey and Git.
Any advice? Thx!

[Ki-test]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/58808904/212131798-77208d11-c370-4342-a0a7-30cd2229da7a.jpg__;!!KGKeukY!yfp-zYI66palpamCCQB8klMsTVAuFCHoJfonXsqsluh1SztbYxigWt6e07sSZ1w7kFGB-w0NVc_VGtW39yEw2LH_TOpYKA$>

**Comment by langfield** [comment]
Yes, this is because you are likely running a Git version less than 2.28.

The way that I will fix this is to catch the exception and use `master` as the branch name for versions under 2.28. Then during pulls, we will use `master` if the `_clone()` call used `master`.

**Comment by AkimParis** [comment]
Thx Langfield! 

Yes, I updated Git, reinstalled Ki, and I successfully cloned my collection.

The running clone command part in the documentation is rather ambiguous for non-native English speakers.
I have written the paragraph in a simpler way below. : ) 

**Running the clone command**

Once you have found the location of the file collection.anki2, we will clone the collection of Anki into a local repository using Ki. The [ki](https://langfield.github.io/ki/#ki) clone command works similarly to the git clone command. 
It will create a new directory called "Collection" for the repository within the current root of the working directory. 

If we want to clone our collection into a new subdirectory, you should make sure that you are in the home directory.   ~/.home/yourusername/) on macOS and GNU/Linux  or  (C:\Users\yourusername\) on Windows 10.

**Anki should be closed before cloning**. Nothing bad will happen but the command will fail because the database is locked. You can run the following ki clone command:

**Comment by langfield** [comment]
Great to hear! I'll look into adding your description to the documentation.

Feel free to open more issues if you have questions or run into trouble, or just want to talk about your use-case!
