### ISSUE TITLE
Clone individual deck instead of collection?

### ISSUE THREAD

**Issue by pwintz** [langfield/ki#17]
Many of the cards in my Anki collection are not compatible with Ki (see Issue #16). Would you please add a feature that allows cloning individual decks into their own Git repos? (Or does this already exist? I see documentation on how to [_clone_ an existing collaborative deck](https://langfield.github.io/ki/#cloning-a-collaborative-deck-from-github) from git, but I don't see how to create one in the first place.

**Comment by langfield** [comment]
@pwintz Hi again! I would definitely be willing to consider adding this feature for you, but I am inclined to fix this problem at its root rather than completely change the architecture and scope of the program if I can avoid it! My intuition is that fixing the Windows filename problem from #16 will get you up and running a lot faster than adding this feature, which I suspect would take a couple of weeks to get in robust shape, naively.

Good eye! I haven't written that yet, and I am so sorry! :cry: Here is a basic outline of the process:

1. Clone your entire collection into a repository.
2. Create an empty repository on Github, or your favorite Git hosting solution (perhaps [SourceHut](sr.ht), which is very cool!).
3. Follow [this procedure](https://gist.github.com/korya/9047870) for converting one of your decks (a subdirectory) into a git submodule, using the git URL for your new empty hosted repository as a remote.

So as you can see, it involves cloning the whole collection, I'm sorry to say! As I said, if we can't get #16 figured out for you, this feature will be the next thing I think about!

**Comment by pwintz** [comment]
Okay, it sounds like the approach you described (cloning the entire collection and then creating a subrepository) is the best short-term fix. I think the ability to clone decks would be a nice-to-have feature, though!

**Comment by langfield** [comment]
Wonderful! I'll keep this issue open until (1) #16, #19, #20, and #22 are resolved, (2) the CI pipeline is passing on Windows, and (3) I've decided whether or not this is something within the scope of the program!

Hope that satisfies you, happy to reconsider if it does not!

**Comment by langfield** [comment]
The CI pipeline is finally passing on Windows (with the symlink error-catching)! I've decided that this is out-of-scope for the moment. Feel free to re-open or open another issue if you strongly disagree! :smile:
