### ISSUE TITLE
`FS_ROOT = Path("/")` causes infinite loop on Windows

### ISSUE THREAD

**Issue by pwintz** [langfield/ki#19]
When running the test method `test_fails_without_ki_subdirectory` on Windows, the test never terminates (the same is true for many other tests). I found that the root cause was that we have a `while` loop with the conditional being `current != FS_ROOT` in `functional.py` where `FS_ROOT` is defined as `FS_ROOT = Path("/")`. This is supposed to test if `current` is the filesystem root and stop the loop when it is, but this doesn't work on Windows because the root directory has a different name.

**Comment by langfield** [comment]
Another brilliant bug report from @pwintz! Let me just say, you are the sort of early user/new contributor that all open-source maintainers dream about. Nice PR! I should be able to get it merged today. I've been working on the [`ki/github-actions`](/langfield/ki/tree/github-actions) branch since yesterday, trying to figure out this _very_ issue, but you beat me to it!

How dumb of me to think it was `pathlib` itself that was broken rather than some code **I** wrote, haha!

**Comment by langfield** [comment]
**Update:** I apologize for not being completely clear when I said I would merge this on Aug 8th. It was technically merged, just not into `main`, lmao. I'd like to bundle all the Windows-related fixes into a single PR, hence the delay. Hope that's all right!
