### ISSUE TITLE
Line ending mismatch in `test_version()` on Windows

### ISSUE THREAD

**Issue by pwintz** [langfield/ki#22]
On Windows, `test_version` fails because the line endings don't match in the assertion. 
The stdout from the command `ki --version` is of `i, version 0.0.1a0\n` but the string it is compared to, namely `f"ki, version {expected_version}{os.linesep}"` evaluates to 'ki, version 0.0.1a0\r\n'.

**Comment by langfield** [comment]
Great catch! Already on it, see [here](https://github.com/langfield/ki/blob/efa2b57a3d40ba48e19652d9a20ac02f17fb200e/tests/test_slow_windows_ci.py#L128-L134). Too bad my attempt at making this cross-platform backfired. :disappointed: I suppose this is not what `os.linesep` is meant for. Will close once this is actually fixed in `tests/test_integration.py`.
