### ISSUE TITLE
Image-only cards are duplicated on `pull`s due to randomly-generated slugs in `get_note_path()`

### ISSUE THREAD

**Issue by langfield** [langfield/ki#27]
Filenames for cards are constructed from the sort field text of the corresponding note. When our sanitization of the sort field content filters out all bytes (i.e. we're left with the empty string), we raise warnings that look like this:

```python
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '8632c30a6504f89b1e26' as filename
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '05f47c5f4df4c30ad262' as filename
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using 'ab909407862c4500feda' as filename
2022-08-08 01:52:32.881 | WARNING  | ki:get_note_path:694 - Slug for '' is empty. Using '27319434ac2a27d6cb7e' as filename
```

The message is more or less useless because we print out the slug instead of the raw or truncated sort field text.

https://github.com/langfield/ki/blob/ed63fef9899b3781c8f4d7663ce7197965f38443/ki/__init__.py#L668-L694

**Comment by langfield** [comment]
After looking at the source for `get_note_path()`, this may be slightly more subtle than I originally thought. We're already using the raw `sort_field_text`, so it's possible this is empty in the note for the cards that raise this warning. Needs further investigation.

**Comment by pwintz** [comment]
It looks like this warning is occurring for cards where the sort field contains no text, only an image.

**Comment by pwintz** [comment]
And this looks like it is a fairly serious problem because all of these cards appear as new cards each time I pull from Anki.

Here is a folder containing a bunch of these cards:
![image](https://user-images.githubusercontent.com/19618780/183875948-3042542f-b1ca-4aca-8a3e-666e8bf283b9.png)

After pulling, the folder has a bunch of new cards despite no cards being created in Anki. 
![image](https://user-images.githubusercontent.com/19618780/183875992-d21ee055-abff-4799-91e5-c6d3fc9a8f04.png)

The merge commit shows these changes (but note that the old files for these cards were not deleted):
![image](https://user-images.githubusercontent.com/19618780/183876390-5806c8d5-51c5-4feb-a298-812623f9ed34.png)

**Comment by langfield** [comment]
This is indeed a serious bug. My thinking is that instead of using a randomly-generated hex string, we could hash the contents of the entire note (so all fields, rather than just the sort field), and use that hash as the filename. This needs more thought. Open to suggestions!

**Comment by pwintz** [comment]
Could we just use the nid as the file name?

**Comment by langfield** [comment]
That's a good idea! My only worry is that since the `nid` is contained in the contents of the card file, we might possibly run into issues where the two get out-of-sync. See below.

https://github.com/langfield/ki/blob/cd0e24e454cfb7537c320f2e430c15f8148fabb6/DEVELOPMENT#L360-L407

**Comment by langfield** [comment]
Naively, though, `nid`s do seem like a better move, since they're robust to changes in the note content itself!
