### ISSUE TITLE
When `ki clone` fails, clean up `collection/` directory

### ISSUE THREAD

**Issue by pwintz** [langfield/ki#29]
When 'ki clone' starts, it creates the 'collection' directory, but if a failure occurs, it does not delete the directory. If you want to run 'ki' again, it's necessary to first manually delete the directory. Could we automatically clean it up (assuming the directory was, in fact, created and didn't already exist)?

**Comment by langfield** [comment]
Haha! Good catch. This is actually a regression, bad me, lol. We have a test for this but it's `xfail`-ed, currently:

https://github.com/langfield/ki/blob/ed63fef9899b3781c8f4d7663ce7197965f38443/tests/test_integration.py#L416-L434

The reason why this is very slightly complex is because we have to treat two cases:

1. The directory doesn't exist, and we're creating it.
2. The directory already exists, is empty, and we're populating it.

My feeling is that when we fail in (1), we must delete the directory, and when we fail in (2), we must delete only its contents.

**Comment by langfield** [comment]
The relevant code is here:

https://github.com/langfield/ki/blob/ed63fef9899b3781c8f4d7663ce7197965f38443/ki/__init__.py#L1596-L1601

Basically, we need to return more information from `get_target()`, and throw a `try`-`except` block in here. Consider it added to the list of priorities!
